-- MySQL Script generated by MySQL Workbench
-- Tue Mar 30 15:24:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gespro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gespro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gespro` DEFAULT CHARACTER SET utf8 ;
USE `gespro` ;

-- -----------------------------------------------------
-- Table `gespro`.`entregable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gespro`.`entregable` (
  `identregable` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `archivo` MEDIUMBLOB NOT NULL,
  `nombreoriginal` VARCHAR(50) NULL DEFAULT NULL,
  `mime` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`identregable`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gespro`.`fase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gespro`.`fase` (
  `idfase` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfase`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gespro`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gespro`.`tipo` (
  `idtipo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gespro`.`fase_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gespro`.`fase_tipo` (
  `idfase_proyecto` INT(11) NOT NULL AUTO_INCREMENT,
  `idtipo` INT(11) NULL DEFAULT NULL,
  `idfase` INT(11) NULL DEFAULT NULL,
  `porcentaje` INT(11) NOT NULL,
  PRIMARY KEY (`idfase_proyecto`),
  INDEX `FK_FASE_idx` USING BTREE (`idfase`) ,
  INDEX `FK_PROYECTO_idx` USING BTREE (`idtipo`) ,
  CONSTRAINT `FK_FASE`
    FOREIGN KEY (`idfase`)
    REFERENCES `gespro`.`fase` (`idfase`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_TIPO`
    FOREIGN KEY (`idtipo`)
    REFERENCES `gespro`.`tipo` (`idtipo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gespro`.`asignacion_entregables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gespro`.`asignacion_entregables` (
  `idasignacion_entregables` INT(11) NOT NULL AUTO_INCREMENT,
  `idfase_proyecto` INT(11) NULL DEFAULT NULL,
  `identregable` INT(11) NULL DEFAULT NULL,
  `porcentaje` INT(11) NOT NULL,
  PRIMARY KEY (`idasignacion_entregables`),
  INDEX `FK_Entregable_idx` (`identregable` ASC) ,
  INDEX `FK_FaseProyecto_idx` USING BTREE (`idfase_proyecto`) ,
  CONSTRAINT `FK_Entregable`
    FOREIGN KEY (`identregable`)
    REFERENCES `gespro`.`entregable` (`identregable`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_FaseTipoAsignacion`
    FOREIGN KEY (`idfase_proyecto`)
    REFERENCES `gespro`.`fase_tipo` (`idfase_proyecto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gespro`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gespro`.`rol` (
  `idrol` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrol`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gespro`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gespro`.`empleado` (
  `idempleado` INT(11) NOT NULL AUTO_INCREMENT,
  `nombrecompleto` VARCHAR(128) NOT NULL,
  `fechaN` VARCHAR(45) NOT NULL DEFAULT '',
  `telefono` VARCHAR(45) NOT NULL,
  `curp` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `domicilio` VARCHAR(45) NOT NULL,
  `gradoestudio` VARCHAR(45) NOT NULL,
  `idrol` INT(11) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `estatus` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idempleado`),
  UNIQUE INDEX `curp_UNIQUE` (`curp` ASC) ,
  INDEX `IDROL_idx` (`idrol` ASC) ,
  CONSTRAINT `IDROL`
    FOREIGN KEY (`idrol`)
    REFERENCES `gespro`.`rol` (`idrol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gespro`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gespro`.`proyecto` (
  `idproyecto` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `duracion` INT(11) NOT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `nombrecliente` VARCHAR(45) NOT NULL,
  `fecha` VARCHAR(45) NOT NULL DEFAULT '',
  `costo` FLOAT NOT NULL,
  `idempleado` INT(11) NULL DEFAULT NULL,
  `idtipo` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idproyecto`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) ,
  INDEX `IDRESPONSABLE_idx` USING BTREE (`idempleado`) ,
  INDEX `IDTIPO_idx` USING BTREE (`idtipo`) ,
  CONSTRAINT `IDRESPONSABLE`
    FOREIGN KEY (`idempleado`)
    REFERENCES `gespro`.`empleado` (`idempleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `IDTIPO`
    FOREIGN KEY (`idtipo`)
    REFERENCES `gespro`.`tipo` (`idtipo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gespro`.`puesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gespro`.`puesto` (
  `idpuesto` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpuesto`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gespro`.`asignar_adscrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gespro`.`asignar_adscrito` (
  `idasignar_adscrito` INT(11) NOT NULL AUTO_INCREMENT,
  `idempleado` INT(11) NULL DEFAULT NULL,
  `idproyecto` INT(11) NULL DEFAULT NULL,
  `idpuesto` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idasignar_adscrito`),
  INDEX `ID_PROYECTO_idx` (`idproyecto` ASC) ,
  INDEX `ID_EMPLEADOINTER_idx` (`idempleado` ASC) ,
  INDEX `ID_PUESTOINTER_idx` (`idpuesto` ASC) ,
  CONSTRAINT `ID_EMPLEADOINTER`
    FOREIGN KEY (`idempleado`)
    REFERENCES `gespro`.`empleado` (`idempleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ID_PROYECTOINTER`
    FOREIGN KEY (`idproyecto`)
    REFERENCES `gespro`.`proyecto` (`idproyecto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ID_PUESTOINTER`
    FOREIGN KEY (`idpuesto`)
    REFERENCES `gespro`.`puesto` (`idpuesto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gespro`.`avance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gespro`.`avance` (
  `idavance` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(256) NOT NULL,
  `idproyecto` INT(11) NULL DEFAULT NULL,
  `archivo` MEDIUMBLOB NOT NULL,
  `terminado` TINYINT(1) NULL DEFAULT NULL,
  `idasignacion_entregables` INT(11) NULL DEFAULT NULL,
  `nombreoriginal` VARCHAR(50) NULL DEFAULT NULL,
  `mime` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idavance`),
  INDEX `ID_PROYECTO_idx` (`idproyecto` ASC) ,
  INDEX `IDASIGNACION_idx` (`idasignacion_entregables` ASC) ,
  CONSTRAINT `IDASIGNACION`
    FOREIGN KEY (`idasignacion_entregables`)
    REFERENCES `gespro`.`asignacion_entregables` (`idasignacion_entregables`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ID_PROYECTO`
    FOREIGN KEY (`idproyecto`)
    REFERENCES `gespro`.`proyecto` (`idproyecto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
